config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :splash, only: [:index]
  resources :groups do
    resources :expenses
  end
  root "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_one_attached :icon

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_one_attached :icon

  validates :name, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, class_name: 'Group', dependent: :destroy, foreign_key: 'user_id'
  has_many :expenses, class_name: 'Expense', dependent: :destroy, foreign_key: 'user_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :find_group

  def new
    @expense = Expense.new
  end

  def create
    unless @group.user == current_user
      return redirect_to groups_path, notice: 'You can only create expenses from your categories'
    end

    if expense_params[:group_ids].length == 1
      return redirect_to new_group_expense_path(@group), alert: 'Must select at least one category'
    end

    @expense = Expense.new(expense_params)
    @expense.user = current_user

    if @expense.save
      flash[:notice] = 'Transaction created successfully'
      @redirect_group = Group.find(expense_params[:group_ids].at(1))
      redirect_to @redirect_group
    else
      flash[:alert] = @expense.errors.full_messages.first if @expense.errors.any?
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end

  def find_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_user

  def index
    @groups = @user.groups.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = @user
    if @group.save
      redirect_to groups_path, notice: 'Category added successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :new, status: 400
    end
  end

  def show
    @group = Group.find(params[:id])
    redirect_to groups_path, notice: 'You are not authorized to access this page!' unless @group.user == @user
    @expenses = @group.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  private

  def set_user
    @user = current_user
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/new.html.erb
<%= render partial: 'shared/header', locals: { heading: 'ADD NEW TRANSACTION', path: group_path(@group) } %>

<%= render 'shared/flash' %>

<%= form_with model: @expense, url: group_expenses_path, local: true do |f| %>
  <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-field" %>
  <%= f.number_field :amount, autofocus: true, placeholder: "Amount", class: "form-field" %>
  <div class="checkbox-btn">
    <%= f.label :group_ids, "Select one or more categories:" %>
    <div class="checkboxes">
      <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :name do |b| %>
        <div>
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
    

    <%= f.submit "Save", class: "btn splash-login" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= render partial: 'shared/header', locals: { heading: 'CATEGORIES', path: groups_path } %>

<%= render 'shared/flash' %>

<div class="content-container">
  <% @groups.each do |group| %>
    <ul>
      <li class="card">
        <%= link_to group_path(group), class: "flex-row" do %>
          <div class="image">
            <% if group.icon.attached?%>
              <%= image_tag(group.icon) %>
            <%else%>
              <%= image_tag('group.png') %>
            <%end%>
          </div>
          <div class="info">
            <div class="name-amount">
              <h3><%= group.name %></h3>
              <h3>$<%= group.expenses.sum(:amount) %></h3>
            </div>
            <p><%= group.created_at.strftime("%d-%m-%Y") %></p>
          </div>
        <% end %>
      </li>
    </ul>
  <% end %>

  <%= link_to new_group_path do %><button class="btn group-btn">Add new category</button><% end %>
</div>

app/views/groups/new.html.erb
<%= render partial: 'shared/header', locals: { heading: 'ADD NEW CATEGORY', path: groups_path } %>

<%= render 'shared/flash' %>

<%= form_with model: @group, url: groups_path, local: true, class: 'form' do |f| %>
  <%= f.text_field :name, autofocus: true, placeholder: "Category Name", class: "form-field" %>
  <div class="checkbox-btn">
    <%= f.file_field :icon %>
    <%= f.submit "Save", class: "btn splash-login" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<%= render partial: 'shared/header', locals: { heading: 'TRANSACTIONS', path: groups_path } %>

<%= render 'shared/flash' %>

<div class="card name-amount p-10">
  <h3><%= @group.name %></h3>
  <h3>$<%= @expenses.sum(:amount) %></h3>
</div>

<div class="content-container">
  <% @expenses.each do |expense| %>
    <ul>
      <li class="flex-row card">
        <div class="image">
          <% if @group.icon.attached?%>
            <%= image_tag(@group.icon) %>
          <%else%>
            <%= image_tag('group.png') %>
          <%end%>
        </div>
        <div class="info">
          <div class="name-amount">
            <h3><%= expense.name %></h3>
            <h3>$<%= expense.amount %></h3>
          </div>
          <p><%= expense.created_at.strftime("%d-%m-%Y") %></p>
        </div>
      </li>
    </ul>
  <% end %>

  <%= link_to new_group_expense_path(group_id: @group.id) do %><button class="btn group-btn">Add new transaction</button><% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="flash flash-<%= type == 'notice' ? 'success' : 'error' %>">
      <p class="<%= type == 'notice' ? 'success' : 'error' %>"><%= msg %></p>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<section class="header">
  <%= link_to(image_tag('back_arrow.png', class: "back"), path) %>
  <h1><%= heading %></h1>
</section>

app/views/splash/index.html.erb
<section class="splash-screen">
  <div class="welcome">
    <h1>Budget App</h1>
  </div>

  <div class="splash-btns">
    <%= link_to new_user_session_path do %><button class="btn splash-login">LOG IN</button><% end %>
    <%= link_to new_user_registration_path do %><button class="btn splash-signup">SIGN UP</button><% end %>
  </div>
</section>